name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker image to Fly.io
        run: |
          flyctl deploy --local-only
          flyctl deploy
